### ISSUE TITLE
Sound FX & Music - Add some sound fx and music for the game

### ISSUE THREAD

**Issue by kaboomblam** [kaboomblam/roots_otaku_game#4]

**Comment by llambert4645** [comment]
Am assuming this is the task that hasn't been assigned, correct?

**Comment by kaboomblam** [comment]
> Am assuming this is the task that hasn't been assigned, correct?

Yes, that's right.

It needs figuring out who should be assigned this. Any ideas @llambert4645 @JMwanza?

**Comment by kaboomblam** [comment]
Added music; mostly from [newgrounds.com](https://www.newgrounds.com/audio) to the game, as well some SoundFX from [opengameart.com](https://opengameart.org/)
